config/routes.rb
Rails.application.routes.draw do

  devise_for :musics

  resources :musics, only: [:index, :show] do
  	resources :episodes
  end

  authenticated :music do
  	root 'musics#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :music

  has_attached_file :episode_thumbnail, :styles => { :large => "1000x1000#", :medium => "550x550#" }
  validates_attachment_content_type :episode_thumbnail, :content_type => /\Aimage\/.*\Z/

  has_attached_file :mp3
  validates_attachment :mp3, :content_type => { :content_type => ["audio/mpeg", "audio/mp3", "audio/mpg"] }, :file_name => { :matches => [/mp3\Z/] }
end

app/models/music.rb
class Music < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :episodes

   
  has_attached_file :thumbnail, :styles => { :large => "1000x1000#", :medium => "550x550#" }
  validates_attachment_content_type :thumbnail, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :title, :thumbnail)}
  	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :thumbnail, :description, :itunes, :stitcher, :podbay)}
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	before_action :authenticate_music!, except: [:show]
	before_action :require_permission
	before_action :find_music
	before_action :find_episode, only: [:show, :edit, :update, :destroy]

	def new
		@episode = @music.episodes.new
	end

	def create
		@episode = @music.episodes.new episode_params
		if @episode.save
			redirect_to music_episode_path(@music, @episode)
		else
			render 'new'
		end
	end

	def show
		@episodes = Episode.where(music_id: @music).order("created_at DESC").limit(6).reject { |e| e.id == @episode.id }
	end

	def edit
	end

	def update
		if @episode.update episode_params
			redirect_to music_episode_path(@music, @episode), notice: "Episode was succesfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@episode.destroy
		redirect_to root_path
	end

	private

	def episode_params
		params.require(:episode).permit(:title, :description, :episode_thumbnail, :mp3)
	end

	def find_music
		@music = Music.find(params[:music_id])
	end

	def find_episode
		@episode = Episode.find(params[:id])
	end

	def require_permission
		@music = Music.find(params[:music_id])
		if current_music != @music
			redirect_to root_path, notice: "Sorry, you're not allowed to view that page"
		end
	end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
	before_action :find_music, only: [:show, :dashboard]
	before_action :find_episode, only: [:show, :dashboard]

	def index
		@musics = Music.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
	end

	def show
	end

	def dashboard
	end

	private

	def find_episode
		@episodes = Episode.where(music_id: @music).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
	end

	def find_music
		if params[:id].nil?
			@music = current_music
		else
			@music = Music.find(params[:id])
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController <ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/episodes/_form.html.erb
<%= form_for ([@music, @episode]) do |f| %>

	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</div>

	<div class="field">
		<%= f.label :episode_thumbnail %><br>
		<%= f.file_field :episode_thumbnail %>
	</div>

	<div class="field">
		<%= f.label :mp3 %><br>
		<%= f.file_field :mp3 %>
	</div>

	<%= f.submit class: "button button_highlight button_block" %>
<% end %>

app/views/episodes/edit.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1>The Flash Music Dashboard</h1>
    </div>
  </div>

  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Episodes", root_path %></li>
        <li><%= link_to "New Episode", new_music_episode_path(@music) %></li>
        <li><%= link_to "Account Settings", edit_music_registration_path %></li>
        <li><%= link_to "View Albums", music_path(current_music) %></li>
      </ul>
    </div>
  </div>

  <div id="form">
	  <div class="wrapper_skinny">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/episodes/new.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1>The Flash Music Dashboard</h1>
    </div>
  </div>

  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Episodes", root_path %></li>
        <li><%= link_to "New Episode", new_music_episode_path(@music), class: "current" %></li>
        <li><%= link_to "Account Settings", edit_music_registration_path %></li>
        <li><%= link_to "View Albums", music_path(current_music) %></li>
      </ul>
    </div>
  </div>

  <div id="form">
	  <div class="wrapper_skinny">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/episodes/show.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @music.title %></h1>
			<p class="description"><%= @music.description %></p>
			<% unless @music.itunes.blank? %>
				<a href="<%= @music.itunes %>" class="subscribe_link">iTunes</a>
			<% end %>
			<% unless @music.stitcher.blank? %>
				<a href="<%= @music.stitcher %>" class="subscribe_link">Stitcher</a>
			<% end %>
			<% unless @music.musicbay.blank? %>
				<a href="<%= @music.musicbay %>" class="subscribe_link">MusicBay</a>
			<% end %>
		</div>
	</div>

	<div id="breadcrumb">
		<%= link_to musics_path do %>
			All Albums
			<span>/</span>
			<%= link_to @music.title, music_path(@music) %>
			<span>/</span>
			<%= @episode.title %>
		<% end %>
	</div>

	<div id="episode_content">
		<div class="wrapper_skinny">
			<%= image_tag @episode.episode_thumbnail.url(:medium), class: "current_episode_thumbnail" %>
			<h2><%= @episode.title %></h2>
			<p class="description"><%= @episode.description %></p>

			<div id="jquery_jplayer_1" class="jp-jplayer"></div>
      <div id="jp_container_1" class="jp-audio">
        <div class="jp-type-single">
          <div class="jp-gui jp-interface">
            <ul class="jp-controls">
              <li><a href="javascript:;" class="jp-play" tabindex="1">&#61515;</a></li>
              <li><a href="javascript:;" class="jp-pause" tabindex="1">&#61516;</a></li>
              <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">&#61480;</a></li>
              <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">&#61478;</a></li>
            </ul>

            <div class="jp-progress">
              <div class="jp-seek-bar">
                <div class="jp-play-bar"></div>
              </div>
            </div>

            <div class="jp-time-holder">
              <div class="jp-current-time"></div>
            </div>

            <div class="jp-volume-bar">
              <div class="jp-volume-bar-value"></div>
            </div>

            <div class="jp-no-solution">
              <span>Update Required</span>
              To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
            </div>
          </div>
        </div>
      </div>
		</div>
	</div>

	<div id="episodes">
		<div class="wrapper_skinny">
			<ul class="cf">
				<% @episodes.each do |episode| %>
					<li class="cf">
						<div class="episode_thumbnail">
							<a href="episode.html">
								<%= image_tag episode.episode_thumbnail.url(:medium) %>
							</a>
						</div>
						<div class="episode_overview">
							<h2><%= link_to episode.title, music_episode_path(@music, episode) %></h2>
							<p class="description"><%= truncate(episode.description, length: 160) %></p>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

<script>
	$(document).ready(function(){
	  $("#jquery_jplayer_1").jPlayer({
	    ready: function () {
	      $(this).jPlayer("setMedia", {
	        mp3: "<%= @episode.mp3.url %>",
	      });
	    },
	    swfPath: "/js",
	    supplied: "mp3"
	  });
	});
</script>

app/views/layouts/_header.html.erb
<header id="main_header" class="cf">
	<div class="wrapper_wide">
		<%= link_to "MusicFlix", root_path, id: "logo" %>
		<nav>
			<ul>
				<% unless music_signed_in? %>
					<li><%= link_to "Explore", musics_path %></li>
					<li><%= link_to "Sign In", new_music_session_path %></li>
					<li><%= link_to "Upload Music", new_music_registration_path %></li>
				<% else %>
					<li><%= link_to "Dashboard", root_path %></li>
					<li><%= link_to "Explore", musics_path %></li>
					<li><%= link_to "Sign Out", destroy_music_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicFlix</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if alert %>
  <div id="notice_wrapper">
    <p class="alert"><%= alert %></p>
  </div>
<% elsif notice %>
  <div id="notice_wrapper">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>

<% unless current_page?(root_path) %>
  <%= render 'layouts/header'; %>
<% end %>

<%= yield %>

<script>
  $(document).ready(function(){
    setTimeout(function() {
      $('#notice_wrapper').fadeOut("slow", function() {
        $this.remove();
      });
    }, 4500 );
  });
</script>

</body>
</html>

app/views/musics/dashboard.html.erb
<%= render 'layouts/header'; %>

<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1>The Flash Music Dashboard</h1>
    </div>
  </div>

  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li class="current">Episodes</li>
        <li><%= link_to "New Episode", new_music_episode_path(@music) %></li>
        <li><%= link_to "Account Settings", edit_music_registration_path %></li>
        <li><%= link_to "View Albums", music_path(current_music) %></li>
      </ul>
    </div>
  </div>

  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <% @episodes.each do |episode| %>
          <li class="cf">
            <div class="episode_thumbnail">
              <a href="episode.html">
                <%= image_tag episode.episode_thumbnail.url(:medium) %>
              </a>
            </div>
            <div class="episode_overview">
              <h2><%= link_to episode.title, music_episode_path(@music, episode) %></h2>
              <p class="description"><%= truncate(episode.description, lenght: 160) %></p>
              <div class="authorized_links">
                <%= link_to "Edit", edit_music_episode_path(@music, episode) %>
                <%= link_to "Delete", music_episode_path(@music, episode), method: :delete, data: {confirm: "Are you sure?"} %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%= will_paginate @episodes, previous_label: "Previous", next_label: "Next" %>

app/views/musics/index.html.erb
<div id="banner" class="podcasts_banner">
	<h1>Discover your new Favourite Music</h1>
</div>

<div id="podcasts" class="cf">
	<div class="wrapper">
		<ul class="cf">
			<% @musics.each do |music| %>
				<%= link_to music do %>
					<li>
						<%= image_tag music.thumbnail.url(:medium) %>
						<div class="podcast_overview">
							<h2><%= music.title %></h2>
							<p class="episode_count">1 Episode</p>
						</div>
					</li>
				<% end %>
			<% end %>
		</ul>

		<%= will_paginate @musics, previous_label: "Previous", next_label: "Next" %>
	</div>
</div>

app/views/musics/show.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @music.title %></h1>
			<p class="description"><%= @music.description %></p>
			<% unless @music.itunes.blank? %>
				<a href="<%= @music.itunes %>" class="subscribe_link">iTunes</a>
			<% end %>
			<% unless @music.stitcher.blank? %>
				<a href="<%= @music.stitcher %>" class="subscribe_link">Stitcher</a>
			<% end %>
			<% unless @music.musicbay.blank? %>
				<a href="<%= @music.musicbay %>" class="subscribe_link">PodBay</a>
			<% end %>
		</div>
	</div>

	<div id="breadcrumb">
		<%= link_to musics_path do %>
			All Musics
			<span>/</span>
			The Flash Music
		<% end %>
	</div>

	<div id="episodes">
		<div class="wrapper_skinny">
			<ul class="cf">
				<% @episodes.each do |episode| %>
					<li class="cf">
						<div class="episode_thumbnail">
							<a href="#">
								<%= image_tag episode.episode_thumbnail.url(:medium) %>
							</a>
						</div>
						<div class="episode_overview">
							<h2><%= link_to episode.title, music_episode_path(@music, episode) %></h2>
							<p class="description"><%= truncate(episode.description, length: 160) %></p>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

<%= will_paginate @episodes, previous_label: "Previous", next_label: "Next" %>

app/views/welcome/index.html.erb
<div id="background">
	<header class="cf">
		<div class="wrapper_wide">
			<a href="#" id="logo">MusicFlix</a>
			<nav>
				<ul>
					<li><%= link_to "Explore", musics_path %></li>
					<li><%= link_to "Sign In", new_music_session_path %></li>
					<li><%= link_to "Upload Music", new_music_registration_path %></li>
				</ul>
			</nav>
		</div>
	</header>
	<div class="wrapper_skinny">
		<h1>Discover your new favorite<br> Music, or create your own.</h1>
		<%= link_to "Upload Music", new_music_registration_path, class: "button button_highlight" %>
		<%= link_to "Explore", musics_path, class: "button button_white" %>
	</div>
</div>