webonlinemovies/movies/urls.py
from django.conf.urls import url
from . import views

app_name = 'movies'
urlpatterns = [
	#/movies/
	url(r'^$', views.index, name = 'index'),
    url(r'^login/$', views.LoginFormView.as_view(), name = 'login'),
    url(r'^register/$',views.RegisterFormView.as_view(),name = 'register'),
    url(r'^main/$', views.index, name = 'index'),
    url(r'^(?P<pk>[0-9]+)/$',views.detail,name = 'detail'),
    url(r'^results/$',views.results,name = 'results'),
    url(r'^logout/$',views.logout,name="logout"),
]

webonlinemovies/webonlinemovies/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^movies/',include('movies.urls')),
    url(r'^', include('movies.urls')),
]

webonlinemovies/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
	movieName = models.CharField(max_length = 100)
	releaseYear = models.CharField(max_length = 10)
	production = models.CharField(max_length = 100)
	genre = models.CharField(max_length = 30)
	imageURL = models.CharField(max_length = 1000,default = "http://www.mvies.com")
	movieURL = models.CharField(max_length = 1000)
	views = models.BigIntegerField(default = 0)
	likes = models.BigIntegerField(default = 0)
	dislikes = models.BigIntegerField(default = 0)

	def __str__(self):
		return self.movieName + "__" + self.releaseYear

webonlinemovies/movies/forms.py
from django.contrib.auth.models import User
from django import forms

class RegisterForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username','email','password']

webonlinemovies/movies/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.template import loader
from django.http import HttpResponse,Http404
from django.contrib.auth import authenticate,login as django_login,logout as django_logout
from django.views import generic
from django .views.generic import View
from django.conf import settings
from .models import Movie
from .forms import RegisterForm
import sys

# # Create your views here.
def index(request):
	if not request.user.is_authenticated:
		return redirect('movies:login')
	
	movieList = []
	try:
		choiceList = request.GET.getlist('choice')
		print(choiceList)
		if len(choiceList) == 0 or 'all' in choiceList:
			print(len(choiceList))
			choiceList = ['all']
			movieList = Movie.objects.all()
		else:
			print(len(choiceList))
			for choice in choiceList:
				try:
					print(choice)
					movieList = movieList | Movie.objects.filter(genre__icontains = choice)
				except:
					movieList = Movie.objects.filter(genre__icontains = choice)
	except:
		movieList = Movie.objects.all()
	
	paginator = Paginator(movieList,12)
	page = request.GET.get('page')
	try:
		movies = paginator.page(page)
	except PageNotAnInteger:
		# If page not an integer deliver first page
		movies = paginator.page(1)
	except EmptyPage:
		# If page is out of range deliver last page
		movies = paginator.page(paginator.num_pages)
	return render(request,'movies/index.html',{'movies':movies,'choiceList':choiceList})

def results(request):
	query = request.GET.get('search')
	movieList = Movie.objects.filter(movieName__icontains = query) | Movie.objects.filter(production__icontains = query)
	paginator = Paginator(movieList,12)
	page = request.GET.get('page')
	try:
		movies = paginator.page(page)
	except PageNotAnInteger:
		# If page not an integer deliver first page
		movies = paginator.page(1)
	except EmptyPage:
		# If page is out of range deliver last page
		movies = paginator.page(paginator.num_pages)
	return render(request,'movies/index.html',{'movies':movies,'search':query})

def detail(request,pk):
	if not request.user.is_authenticated:
		return redirect('movies:login')	

	movie = Movie.objects.get(pk = pk)
	movie.views += 1
	movie.save() 
	genre = movie.genre
	genreList = genre.split(';')
	movieList = []
	print(genreList)
	for genre in genreList:
		try:
			movieList = movieList | Movie.objects.filter(genre__icontains = genre)
		except:
			movieList = Movie.objects.filter(genre__icontains = genre)
	
	movieList = movieList.exclude(pk = movie.pk)
	movieList = movieList[:8]

	return render(request,'movies/detail.html',{'movie':movie,'movies':movieList})

class LoginFormView(View):
	template_name = 'movies/login.html'

	def get(self,request):
		return render(request,self.template_name)

	def post(self,request):
		username = request.POST['username']
		password = request.POST['password']
		
		user = authenticate(username = username,password = password)
		print(user)
		if user is not None:
			print('Not none',user)
			if  user.is_active:
				print('Active',user)
				django_login(request,user)
				return redirect("movies:index")
		else:
			print('Form is not valid')
			return render(request,self.template_name) 			

def logout(request):
	if request.user.is_authenticated:
		print('User is currently logged in and is requesting logout')
		django_logout(request)
		return redirect('movies:login')
	else:
		return redirect('movies:login')

class RegisterFormView(View):
	form_class = RegisterForm
	template_name = 'movies/register.html'

	def get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit = False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			email = form.cleaned_data['email']
			print(username,email,password)
			user.set_password(password)
			user.save()

			user = authenticate(username = username, password = password)
			print(user)
			if user is not None:
				print('Not none',user)
				if  user.is_active:
					print('Active',user)
					django_login(request,user)
					return redirect("movies:index")
		return render(request,self.template_name,{'form':form})

webonlinemovies/movies/templates/movies/detail.html
{% extends 'movies/main.html' %}

{% block title %}Watch Movie{% endblock %}

{% block styleSheets %}
	{% load staticfiles %}
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <link rel="stylesheet" type="text/css" href="{% static 'movies/movies_css/detail.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'movies/movies_css/index.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'movies/movies_css/sidebar.css' %}">
  <script type="text/javascript" src="{% static 'movies/JavaScript/sidebar.js' %}"></script>
{% endblock %}

{% block body %}

{%if movie %}
	<div class="row playingClass">
		<div class="col-md-8 videoPlayer">
			<div class="embed-responsive embed-responsive-16by9">
				<iframe class="container"  src="{{ movie.movieURL }}" frameborder="0" allowfullscreen></iframe>
			</div>
		</div>
		<div class="col-md-4 detailClass">
			<div class="col-md-12 imageContainer">
				<img class="imageClass" src="{{movie.imageURL}}" alt="movieImage">
			</div>
			<div class="col-md-12" align="center">
				<h3>{{movie.movieName}}</h3>
				<h3>{{movie.production}}</h3>
				<h4>{{movie.views}} views</h4>
				<div class="col-md-offset-4 col-md-2">
					<img class="votes" src="https://upload.wikimedia.org/wikipedia/commons/1/13/Facebook_like_thumb.png" alt="Like">
                    {{movie.likes}}
				</div>
				<div class="col-md-2">
					<img class="votes" src="http://applemagazine.com/wp-content/uploads/2014/12/facebook-dislike.png" alt="Dislike">
                    {{movie.dislikes}}
				</div>
			</div>
		</div>
	</div>

	<div style="margin-top: 20px;" align="center">
    <div class="container">
      {% for movie in movies %}
        <div class="item {% if forloop.first %} active {% endif %}" style="display: inline-block;">
        <a class="card-link" href="{% url 'movies:detail' movie.id%}">
          <div class="card">
              <div class="card_image">
                  <img src="{{movie.imageURL}}" alt="MovieImage">
              </div>
              <div class="card_content row-md-6">
                  <div class="description">
                    <h3>{{movie.movieName}}</h3>
                    <h4>{{movie.production}}</h4>
                    <div class="extra">
                        <span>{{movie.views}}views</span>
                        <span>
                            <img src="https://upload.wikimedia.org/wikipedia/commons/1/13/Facebook_like_thumb.png" alt="Like">
                            {{movie.likes}}
                        </span>
                        <span>
                            <img src="http://applemagazine.com/wp-content/uploads/2014/12/facebook-dislike.png" alt="Dislike">
                            {{movie.dislikes}}
                        </span>
                    </div>
                  </div>
              </div>
            </div>
        </a>
       </div>
      {% endfor %}
    </div>
	</div> 

  {%else%}
	 <p>No movies present</p>
  {%endif%}

{% endblock %}

webonlinemovies/movies/templates/movies/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Login{% endblock %}</title>

    <link href="https://fonts.googleapis.com/css?family=Parisienne|Sedgwick+Ave" rel="stylesheet">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'movies/movies_css/register.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'movies/movies_css/header.css' %}">
    
    {% block styleSheets %}{% endblock %}
</head>
<body>
  <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="container-fluid">

        <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topNavBar" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            
            <a class="navbar-brand" href="{% url 'movies:index'%}">
              <span>
                <img src="{% static 'movies/images/Movie-Club-logo.png'%}" width="30" height="30" style="display:block-inline" alt="logo">
                Movies
              </span>
            </a>
          </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="topNavBar">
            <a href="{% url 'movies:register' %}" class="nav navbar-right authLink">
              <div>Register</div>
            </a>
            <a href="{% url 'movies:login' %}" class="nav navbar-right authLink">
              <div>Login</div>
            </a>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
  
      <div>
        {% block body%}
        {% endblock %}
      </div>
</body>
</html>

webonlinemovies/movies/templates/movies/index.html
{% extends 'movies/main.html' %}

{% block title %}Movies{% endblock %}

{% block styleSheets %}
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'movies/movies_css/index.css' %}">
{% endblock %}

{% block body %}
  
  {% if movies %}
    <div class="section">
      
      {% for movie in movies %}
        <a class="card-link" href="{% url 'movies:detail' movie.id%}">

        	<div class="card">
            <div class="card_image">
              <img src="{{movie.imageURL}}" alt="MovieImage">
            </div>
            <div class="card_content row-md-6">
              <div class="description">
                <h3>{{movie.movieName}}</h3>
                <h4>{{movie.production}}</h4>
                <div class="extra">
                    <span>{{movie.views}}views</span>
                    <span>
                        <img src="https://upload.wikimedia.org/wikipedia/commons/1/13/Facebook_like_thumb.png" alt="Like">
                        {{movie.likes}}
                    </span>
                    <span>
                        <img src="http://applemagazine.com/wp-content/uploads/2014/12/facebook-dislike.png" alt="Dislike">
                        {{movie.dislikes}}
                    </span>
                </div>
              </div>
            </div>
          </div>
          
		    </a>
      {% endfor%}

    {% if movies.has_other_pages %}
    <div align="center">
      <ul class="pagination">
        {% if movies.has_previous %}
          <li><a href="?page={{ movies.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
      
        {% for i in movies.paginator.page_range %}
          {% if movies.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
    
        {% if movies.has_next %}
          <li><a href="?page={{ movies.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}

  </div>

  {% else %}
    <p>No movies are present</p>
  {% endif %}

{% endblock %}

webonlinemovies/movies/templates/movies/login.html
{% extends 'movies/header.html' %}

{% block title %}Login{% endblock %}

{% block body %}

      <div class="container-fluid" style="margin-top:61px;padding: 0px;" align="center">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <img src="https://s-media-cache-ak0.pinimg.com/originals/61/da/5d/61da5d9c8ce5efdd3b3436cd41a36bd0.jpg" alt="movie">
              </div>

              <div class="item">
                <img src="https://cdn.allwallpaper.in/wallpapers/1920x1080/267/dicaprio-hollywood-movie-posters-3d-james-cameron-1920x1080-wallpaper.jpg" alt="Chicago">
              </div>

              <div class="item">
                <img src="http://7wallpapers.net/wp-content/uploads/4_The-Conjuring-2.jpg" alt="New York">
              </div>

              <div class="item">
                <img src="https://s-media-cache-ak0.pinimg.com/originals/40/93/ad/4093ad3915a87509045893fbb00e156a.jpg" alt="New York">
              </div>

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
      </div>

      <div class="container login register" id="loginForm" style="margin-top: 71px">
        <div align="center">
          <h1>Login</h1>
        </div>
        <form action="" method="post">
          {% csrf_token %}
          <div class="row form-group form-inline">
            <label class="control-label col-md-offset-1 col-md-2" for='username'>Username</label>
            <input class="col-md-8 inputType" type="text" control="form-control" name="username" id="username" required="true">
          </div>
          <div class="row form-group">
            <label class="control-label col-md-offset-1 col-md-2" for='password'>Password</label>
            <input class="col-md-8 inputType" type="password" control="form-control" name="password" id="password" required="true">
          </div>
          <div align="center">
            <button type="submit" class="btn btn-success submitButton">Submit</button>
          </div>
        </form>
      </div>

{% endblock %}

webonlinemovies/movies/templates/movies/register.html
{% extends 'movies/header.html' %}

{% block title %}Register{% endblock %}

{% block body %}

      <div class="container-fluid" style="margin-top:61px;padding: 0px;" align="center">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <img src="https://s-media-cache-ak0.pinimg.com/originals/61/da/5d/61da5d9c8ce5efdd3b3436cd41a36bd0.jpg" alt="movie">
              </div>

              <div class="item">
                <img src="https://cdn.allwallpaper.in/wallpapers/1920x1080/267/dicaprio-hollywood-movie-posters-3d-james-cameron-1920x1080-wallpaper.jpg" alt="Chicago">
              </div>

              <div class="item">
                <img src="http://7wallpapers.net/wp-content/uploads/4_The-Conjuring-2.jpg" alt="New York">
              </div>

              <div class="item">
                <img src="https://s-media-cache-ak0.pinimg.com/originals/40/93/ad/4093ad3915a87509045893fbb00e156a.jpg" alt="New York">
              </div>

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
        </div>
      </div>

      <div class="container register" id="registerForm" align="center">
        <div align="center">
          <h1>Register</h1>
        </div>
        <form action="" method="post">
          {% csrf_token %}
          <div class="row form-group">
            <label class="control-label col-md-offset-1 col-md-2" for='username'>Username</label>
            <input class="col-md-8 inputType" type="text" control="form-control" name="username" id="username" required="true">
          </div>
          <div class="row form-group">
            <label class="control-label col-md-offset-1 col-md-2" for='email'>Email</label>
            <input class="col-md-8 inputType" type="email" control="form-control" name="email" id="email" required="true">
          </div>
          <div class="row form-group">
            <label class="control-label col-md-offset-1 col-md-2" for='password'>Password</label>
            <input class="col-md-8 inputType" type="password" control="form-control" name="password" id="password" required="true">
          </div>
          <div align="center">
            <button type="submit" class="btn btn-success submitButton">Submit</button>
          </div>
        </form>
      </div>

{% endblock %}

webonlinemovies/movies/templates/movies/sidebar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Sidebar</title>

    <link href="https://fonts.googleapis.com/css?family=Parisienne|Sedgwick+Ave" rel="stylesheet">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script  src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- {% block styleSheets %}{% endblock %} -->
    <link rel="stylesheet" type="text/css" href="C:\Users\Admin\Desktop\WebProject\Webbased-Multimedia-Streaming\webonlinemovies\movies\static\movies\css\sidebar.css">
  </head>
  
  <body>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li><a href="#">Account</a></li>
                <li><a href="#">Account</a></li>
                <li><a href="#">Account</a></li>
            </ul>
        </div>

        <!-- MainContent -->
        <div id="page-wrapper">
            <div class="conatiner-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <a href="#" class="btn btn-success" id="menu-toggle">Toggle Menu</a>
                        <h1>Side Bar 1</h1>
                        <h1>Side Bar 2</h1>
                        <h1>Side Bar 3</h1>
                        <h1>Side Bar 4</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $('#menu-toggle').click(function(e){
            console.log("cdsc");
            e.preventDefault();
            $('#wrapper').toggleClass('menuDisplayed');
        });
    </script>
  </body>

</html>